---
jobs:
- name: build-task-image
  serial: true
  plan:
  - get: repo-image
    trigger: true
  - put: ciimage
    params:
      build: repo-image/ci/ci_image
# - name: deploy-concourse
#   serial: true
#   plan:
#   - get: repo
#     trigger: true
#   - get: ciimage
#     passed: [build-task-image]
#     trigger: true
#   - task: check-out-bosh
#     image: ciimage
#     config:
#       platform: linux
#       inputs:
#         - { name: repo }
#       run:
#         path: repo/ci/bin/boo.sh

- name: bosh-login
  plan:
  - aggregate:
    - get: repo
      trigger: true
    - get: ciimage
      passed: [build-task-image]
      trigger: true
  - task: bosh-login
    image: ciimage
    config:
      platform: linux
      inputs:
        - { name: repo }
      run:
        dir: repo
        path: ci/bin/bosh-login
    params:
      bosh_director: {{bosh-director}}
      BOSH_USER: {{bosh-username}}
      BOSH_PASSWORD: {{bosh-password}}

resources:
- name: repo
  type: git
  source:
    uri: https://github.com/starkandwayne/concourse-tutorial.git
    branch: set-up-ci
    ignore_paths: [ci/ci_image/*]
- name: repo-image
  type: git
  source:
    uri: https://github.com/starkandwayne/concourse-tutorial.git
    branch: set-up-ci
    paths: [ci/ci_image/*]
- name: ciimage
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: starkandwayne/concourse-tutorial-ci
